ARG IMG="devcon-dev-base"
ARG TAG="latest"

FROM $IMG:$TAG
ARG DEV_USER=devuser

RUN sudo useradd ${DEV_USER}; \
sudo usermod -aG sudo ${DEV_USER}; \
printf "%s ALL=(ALL:ALL) NOPASSWD: ALL\n" "${DEV_USER}" >> /etc/sudoers; \
ls -l /etc/sudoers; \
cat /etc/sudoers; \
id ${DEV_USER}; 


USER ${DEV_USER}
WORKDIR /var/home/${DEV_USER}
